spring.application.name=stemulator-api

spring.ai.openai.api-key=${OPENAI_API_KEY}
#spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.model=gpt-5.4-mini
spring.ai.openai.chat.options.temperature=0.2  

spring.data.mongodb.uri=${MONGO_DB_URL}

